### ISSUE TITLE
To try out the demo CLI chat application question

### ISSUE THREAD

**Issue by zcr268** [named-data/ndn-svs#12]
./waf configure --enable-static --disable-shared --with-examples
./waf
./build/examples/chat /abc

in MacOS 
libc++abi: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<ndn::security::transform::PrivateKey::Error> >: Digest is not supported for key type NONE

**Comment by pulsejet** [comment]
Fixed when using latest ndn-cxx
