### ISSUE TITLE
ndn-svs pubsub API problem

### ISSUE THREAD

**Issue by matianxing1992** [named-data/ndn-svs#15]
It takes a long time to warm up if the producer has already produced lots of updates before the consumer joins (In this case, the consumer only needs the data produced after its joining).

There are several possible solutions mentioned in the emails, and they are:

1/ We could ignore the very first Sync Interest that is received for the purpose of fetching data. This however will not work well in adhoc scenarios or if you also want to ignore data that was produced during a network partition.
2/ Another way would be to specify the maximum number of packets to catch up in the past
3/ It might be worth considering extending the mapping data to include the time of publication, so we can do #3, but for publications newer than a certain time point instead of count.

**Comment by pulsejet** [comment]
https://github.com/named-data/StateVectorSync/pull/10#pullrequestreview-1433294483
